# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('duration', models.DurationField()),
                ('timezone', models.CharField(choices=[('ET', 'Eastern'), ('CT', 'Central'), ('MT', 'Mountain'), ('PT', 'Pacific')], default='CT', max_length=2)),
                ('name', models.TextField(max_length=256)),
                ('location', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('repeats', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
